<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <ApplicationDefaultFont>Segoe UI, 10pt</ApplicationDefaultFont>
    <AssemblyName>KontrolniProtokol</AssemblyName>
    <RootNamespace>KontrolniProtokol</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Management" Version="8.0.0" />
    <PackageReference Include="ClosedXML" Version="0.102.3" />
    <PackageReference Include="LibreHardwareMonitorLib" Version="0.9.3" />
    <PackageReference Include="AForge.Video.DirectShow" Version="2.2.5" />
  </ItemGroup>
</Project>
